[project]
name = "my_study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=24.10.0",
    "ruff>=0.9.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
